#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound} security configuration (this key should be unique for your application, and kept secret)
security.rememberme.key=activitis3cr3tk3y

${symbol_pound}datasource.driver=org.h2.Driver
${symbol_pound}datasource.url=jdbc:h2:tcp://localhost:9092/activiti-admin
${symbol_pound}datasource.username=alfresco
${symbol_pound}datasource.password=alfresco

${symbol_pound}datasource.driver=org.postgresql.Driver
${symbol_pound}datasource.url=jdbc:postgresql://postgre:5432/activiti-admin?characterEncoding=UTF-8
${symbol_pound}datasource.username=alfresco
${symbol_pound}datasource.password=alfresco

datasource.driver=org.h2.Driver
datasource.url=jdbc:h2:mem:db1;DB_CLOSE_DELAY=1000
datasource.username=sa
datasource.password=

${symbol_pound} H2 example

${symbol_pound}datasource.driver=org.h2.Driver
${symbol_pound}datasource.url=jdbc:h2:tcp://localhost/activiti-admin

${symbol_pound} MySQL example

${symbol_pound}datasource.driver=com.mysql.jdbc.Driver
${symbol_pound}datasource.url=jdbc:mysql://127.0.0.1:3306/activitiadmin?characterEncoding=UTF-8

${symbol_pound}datasource.driver=org.postgresql.Driver
${symbol_pound}datasource.url=jdbc:postgresql://localhost:5432/activitiadmin

${symbol_pound}datasource.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
${symbol_pound}datasource.url=jdbc:sqlserver://localhost:1433;databaseName=activitiadmin

${symbol_pound}datasource.driver=oracle.jdbc.driver.OracleDriver
${symbol_pound}datasource.url=jdbc:oracle:thin:@localhost:1521:ACTIVITIADMIN

${symbol_pound}datasource.driver=com.ibm.db2.jcc.DB2Driver
${symbol_pound}datasource.url=jdbc:db2://localhost:50000/activitiadmin

${symbol_pound}datasource.username=activiti
${symbol_pound}datasource.password=

${symbol_pound} JNDI CONFIG

${symbol_pound} If uncommented, the datasource will be looked up using the configured JNDI name.
${symbol_pound} This will have preference over any datasource configuration done below that doesn't use JNDI
${symbol_pound}
${symbol_pound} Eg for JBoss: java:jboss/datasources/activitiDS
${symbol_pound}
${symbol_pound}datasource.jndi.name=jdbc/activitiDS

${symbol_pound} Set whether the lookup occurs in a J2EE container, i.e. if the prefix "java:comp/env/" needs to be added if the JNDI
${symbol_pound} name doesn't already contain it. Default is "true".
${symbol_pound}datasource.jndi.resourceRef=true

hibernate.dialect=org.hibernate.dialect.H2Dialect
${symbol_pound}hibernate.dialect=org.hibernate.dialect.MySQLDialect
${symbol_pound}hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
${symbol_pound}hibernate.dialect=org.hibernate.dialect.SQLServerDialect
${symbol_pound}hibernate.dialect=org.hibernate.dialect.DB2Dialect
${symbol_pound}hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
${symbol_pound}hibernate.show_sql=false
${symbol_pound}hibernate.generate_statistics=false

${symbol_pound}
${symbol_pound} Connection pool (see http://www.mchange.com/projects/c3p0/${symbol_pound}configuration)
${symbol_pound}

${symbol_pound}datasource.min-pool-size=5
${symbol_pound}datasource.max-pool-size=100
${symbol_pound}datasource.acquire-increment=5
${symbol_pound} test query for H2, MySQL, PostgreSQL and Microsoft SQL Server
${symbol_pound}datasource.preferred-test-query=select 1
${symbol_pound} test query for Oracle
${symbol_pound}datasource.preferred-test-query=SELECT 1 FROM DUAL
${symbol_pound} test query for DB2
${symbol_pound}datasource.preferred-test-query=SELECT current date FROM sysibm.sysdummy1
${symbol_pound}datasource.test-connection-on-checkin=true
${symbol_pound}datasource.test-connection-on-checkout=true
${symbol_pound}datasource.max-idle-time=1800
${symbol_pound}datasource.max-idle-time-excess-connections=1800

${symbol_pound}
${symbol_pound} Cluster settings
${symbol_pound}

${symbol_pound} This a period of time, expressed in milliseconds, that indicates
${symbol_pound} when a node is deemed to be inactive and is removed from the list
${symbol_pound} of nodes of a cluster (nor will it appear in the 'monitoring' section of the application).
${symbol_pound}
${symbol_pound} When a node is properly shut down, it will send out an event indicating
${symbol_pound} it is shut down. From that point on, the data will be kept in memory for the amount
${symbol_pound} of time indicated here.
${symbol_pound} When a node is not properly shut down (eg hardware failure), this is the period of time
${symbol_pound} before removal, since the time the last event is received.
${symbol_pound}
${symbol_pound} Make sure the value here is higher than the sending interval of the nodes, to avoid
${symbol_pound} that nodes incorrectly removed.
${symbol_pound}
${symbol_pound} By default 10 minutes
cluster.monitoring.max.inactive.time=600000

${symbol_pound} A cron expression that configures when the check for inactive nodes is made.
${symbol_pound} When executed, this will mark any node that hasn't been active for 'cluster.monitoring.max.inactive.time'
${symbol_pound} seconds, as an inactive node. Default: every 5 minutes.
cluster.monitoring.inactive.check.cronexpression=0 0/5 * * * ?

${symbol_pound} REST endpoint config
rest.app.name=Activiti app
rest.app.description=Activiti app Rest config
rest.app.host=http://aps-current-project
rest.app.port=8080
rest.app.contextroot=activiti-app
rest.app.restroot=api
rest.app.user=admin@app.activiti.com
rest.app.password=admin

${symbol_pound} Passwords for rest endpoints and master configs are stored encrypted in the database using AES/CBC/PKCS5PADDING
${symbol_pound} It needs a 128-bit initialization vector (http://en.wikipedia.org/wiki/Initialization_vector)
${symbol_pound} and a 128-bit secret key represented as 16 ascii characters below
${symbol_pound}
${symbol_pound} Do note that if these properties are changed after passwords have been saved, all existing passwords
${symbol_pound} will not be able to be decrypted and the password would need to be reset in the UI.
security.encryption.credentialsIVSpec=j8kdO2hejA9lKmm6
security.encryption.credentialsSecretSpec=9FGl73ngxcOoJvmL

${symbol_pound} BPMN 2.0 Modeler config

modeler.url=https://activiti.alfresco.com/activiti-app/api/
